jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: "H0GO0A4SC84086wc2CLZRVkL2LZYaQTThPgQFbOKMzaLSywXgUL0seaEHmK0Neza6CJtwSj7gvhiAXIt1nhRZdWejVLxK/1KdoUReId7vv7+h9bM8+IofrsVW0WMtDw0D3hhaEzvUWJTVdrpeAA4cIOnnLdS11DL1Ok2JzHQc+vTgBiqLCemAjaDnm7K+CZT8TmlIsJWQ50Sa7c71DrateZM32x99PxZl4w5lJPbjFP3kWgyC/YCGs+V3jZ0OXJtoH3P+p2lHTsDZSY7SxJy/nLcKhlrpJJ8ccUhg8HhIpXVTKsRrCTlTjAPyX5Em5RFurFFbltDY8p5Vn9xWLDfaHtelSG2UpBjx1ipCuIFIIbgLdsVtuWza3vjCmQbZ5WlASePf7MglbKy6QF2h2kKMuc1lRz+e5tfV59EeihCZ+gq+ppD4AIvMMz/4dyGpZ/McddybrDMjzx2nBTmvuD+KJfEzjTdF/uzIOEUkKWCDotXqEuloz5Pc8Im5oILru8E1+OeWwfQRvQwYlRka/2cLHjHbCOyTkE/2xZAR1bSE7JEyzF8GLG+HOgfv8oAzq89XkB1iNGb5fWkQ5wGY4PDWVXykVuMc56ZEz60uXvTIJvThnF5r3XXM/VGInswxa0PaUwpqbizkFM5zAjI4UatX5RA5dg2t7hA5lZ5va+I7e4="
        secrets:
          - kv_api_ver: kv2
#           - namespace:
#             - name: ns1
#             - language_used/compiler
          - ns1/language_used
          - ns1/language_used/compiler
#           - ns2/project_id/secret_key_b
      script:
        - echo $LANGUAGE_USED
        - echo $COMPILER
#         - python --version
#         - python hello_world.py
#         - $SECRET_KEY_B
